### ISSUE TITLE
‘-fcf-protection=full’ is not supported on Raspberry Pi

### ISSUE THREAD

**Issue by alex-lt-kong** [oatpp/oatpp#872]
I am trying to build Oatpp on Raspberry Pi 3 Model B Rev 1.2, my system's information is as follows:

```
Architecture:   aarch64
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

Running `cmake ../` complains the following:
```
...
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindThreads.cmake:228 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:314 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/repos/oatpp/build/CMakeFiles/CMakeOutput.log".
See also "/root/repos/oatpp/build/CMakeFiles/CMakeError.log".
```

It says "Could NOT find Threads (missing: Threads_FOUND)" but this couldn't be the case as I am using `pthread` on the same device myself too (and I also use CMakeLists.txt, but I don't specify `find_package(Threads REQUIRED)` though).

After examining `/root/repos/oatpp/build/CMakeFiles/CMakeError.log`:

```
Performing C++ SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /root/repos/oatpp/build/CMakeFiles/CMakeScratch/TryCompile-YvNNHD

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_5e81e/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_5e81e.dir/build.make CMakeFiles/cmTC_5e81e.dir/build
gmake[1]: Entering directory '/root/repos/oatpp/build/CMakeFiles/CMakeScratch/TryCompile-YvNNHD'
Building CXX object CMakeFiles/cmTC_5e81e.dir/src.cxx.o
/usr/bin/c++ -DCMAKE_HAVE_LIBC_PTHREAD  -Wall -Wextra -g3 -Wcast-align -Wconversion -Wdouble-promotion -Winvalid-pch -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wpointer-arith -Wredundant-decls -Wshadow -Wsign-conversion -Wsuggest-attribute=noreturn -Wswitch-default -Wswitch-enum -Wtype-limits -Wundef -Wuninitialized -Wunknown-pragmas -Wunsafe-loop-optimizations -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-function -Wunused -Wunused-label -Wunused-macros -Wunused-result -Wunused-value -Wunused-variable -Wunused-local-typedefs -Wformat=2 -Wsuggest-attribute=format -Wformat-signedness -Wduplicated-cond -Wlogical-op -Wnull-dereference -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=2 -Wsuggest-attribute=cold -Wsuggest-attribute=malloc -Warith-conversion -ftrivial-auto-var-init=zero -Warray-compare -Wbidi-chars=unpaired,ucn -Winfinite-recursion -Wopenacc-parallelism -Wtrivial-auto-var-init -Wctor-dtor-privacy -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wsign-promo -Wstrict-null-sentinel -Wzero-as-null-pointer-constant -Wuseless-cast -Wconditionally-supported -Wsuggest-override -Wnoexcept-type -Wextra-semi -Wcomma-subscript -Wmismatched-tags -Wredundant-tags -Wvolatile -Wctad-maybe-unsupported -Wdeprecated-enum-enum-conversion -Wdeprecated-enum-float-conversion -Winvalid-imported-macros -Wrange-loop-construct -fdata-sections -ffunction-sections -fno-common -Wl,--gc-sections -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fstack-clash-protection -fstack-protector-strong -grecord-gcc-switches -fcf-protection -pipe -Werror=format-security -Wno-format-nonliteral -fPIE -Wl,-z,defs -Wl,-z,now -Wl,-z,relro -Wno-unused-parameter -Wno-pessimizing-move  -o CMakeFiles/cmTC_5e81e.dir/src.cxx.o -c /root/repos/oatpp/build/CMakeFiles/CMakeScratch/TryCompile-YvNNHD/src.cxx
cc1plus: error: ‘-fcf-protection=full’ is not supported for this target
gmake[1]: *** [CMakeFiles/cmTC_5e81e.dir/build.make:78: CMakeFiles/cmTC_5e81e.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/root/repos/oatpp/build/CMakeFiles/CMakeScratch/TryCompile-YvNNHD'
gmake: *** [Makefile:127: cmTC_5e81e/fast] Error 2
```

It turns out that `-fcf-protection=full` causes the issue. A global text search
```
grep --recursive --line-number --word-regexp '../' -e 'fcf-protection'
../cmake/compiler-flags.cmake:255:  add_compiler_flags(4.6 "-fcf-protection")
```
shows it is defined in `../cmake/compiler-flags.cmake:255`, after commenting out this flag, the project compiles as before.

Not sure if this flag bears some significant consequence though.

**Comment by lganzzzo** [comment]
Hello @alex-lt-kong ,
Thanks for sharing this issue!

I think it might be a good idea to comment it out.
Please feel free to send a PR

**Comment by alex-lt-kong** [comment]
Hi @lganzzzo ,

Sure, let me open a PR on this later today.

**Comment by fhuberts** [comment]
Fixed in the wrong way, see https://github.com/oatpp/oatpp/pull/873/files#r1369056392

**Comment by sgallou** [comment]
Still wrong fix, just work for local build, don't work for cross-builds (build for Raspberry from Ubuntu).
